---
info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
---
grails:
  profile: rest-api
  codegen:
    defaultPackage: filequotacontrol
  gorm:
    reactor:
      events: false
  controllers:
    defaultScope: singleton
    upload:
      maxFileSize: 2000000
      maxRequestSize: 2000000
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      json:
        - application/json
        - text/json
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      js: text/javascript
      rss: application/rss+xml
      text: text/plain
      all: '*/*'
  urlmapping:
    cache:
      maxsize: 1000
  converters:
    encoding: UTF-8
  plugin:
    databasemigration:
      updateOnStart: true
      updateOnStartFileName: changelog.groovy
  dataSource:
    dbCreate: none
    pooled: true
    jmxExport: true
  hibernate:
    cache:
      queries: false
      use_second_level_cache: false
      use_query_cache: false
---
spring:
  jmx:
    unique-names: true
  main:
    banner-mode: "off"
  groovy:
    template:
      check-template-location: false
  devtools:
    restart:
      additional-exclude:
        - '*.gsp'
        - '**/*.gsp'
        - '*.gson'
        - '**/*.gson'
        - 'logback.groovy'
        - '*.properties'
